version: '3'
services:
  php:
    image: serversideup/php:8.0-fpm-nginx
    networks:
      - pokedex
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'pokedex-mysql:/var/lib/mysql'
    networks:
      - pokedex
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
    pokedex:
        driver: bridge

volumes:
  pokedex-mysql:
    driver: local